# -*- coding: utf-8 -*-
"""Optimus_Stratus_ImageClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4JCE-0QoYl4_Cyf-alJW4OPpvxkBe5c
"""

#CELL 1 — Install & imports
!pip install -q tensorflow numpy pillow tqdm scikit-learn matplotlib

import os, glob, math, numpy as np, tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from tensorflow.keras import layers, models, callbacks, optimizers
from tqdm import tqdm

print("TF version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 2 — Mount Drive & configure paths  (CORRECTED)     ║
# ╚══════════════════════════════════════════════════════════╝
from google.colab import drive
drive.mount('/content/drive')

# ── Edit this to match your Drive location ────────────────
BASE_DIR = "/content/drive/MyDrive/Optimus_Stratus_dataset"

TRAIN_DIR = os.path.join(BASE_DIR, "training")
VAL_DIR   = os.path.join(BASE_DIR, "validation")
TEST_DIR  = os.path.join(BASE_DIR, "testing")

IMG_SIZE = 96
BATCH    = 32
AUTOTUNE = tf.data.AUTOTUNE

CKPT_PATH  = "/content/model_best.weights.h5"
TFLITE_OUT = "/content/drive/MyDrive/cloud_classifier.tflite"

# Verify TFRecords are visible across all splits and classes
for split, path in [("training", TRAIN_DIR), ("validation", VAL_DIR), ("testing", TEST_DIR)]:
    for cls in ["Cloudy", "NonCloudy"]:
        cls_path = os.path.join(path, cls)
        n = len(glob.glob(os.path.join(cls_path, "*.tfrecord")))
        print(f"  {split:12s} / {cls:10s} : {n} TFRecords")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 3 — Replace augment() with stronger version        ║
# ╚══════════════════════════════════════════════════════════╝
def augment(img, label):
    # Geometric
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_flip_up_down(img)

    # Stronger photometric — matches real satellite variability
    img = tf.image.random_brightness(img, 0.3)      # was 0.15
    img = tf.image.random_contrast(img, 0.6, 1.4)   # was 0.8, 1.2
    img = tf.image.random_saturation(img, 0.7, 1.3) # new
    img = tf.image.random_hue(img, 0.05)             # new — subtle hue shift

    # Random gamma correction — simulates atmospheric scattering
    gamma = tf.random.uniform([], 0.7, 1.4)
    img   = tf.pow(img, gamma)

    # Random channel-wise scaling — simulates band calibration drift
    channel_scale = tf.random.uniform([3], 0.85, 1.15)
    img = img * channel_scale

    img = tf.clip_by_value(img, 0.0, 1.0)
    return img, label

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 3 — Parser that skips corrupt records              ║
# ╚══════════════════════════════════════════════════════════╝
FEATURE_DESC = {
    "image":    tf.io.FixedLenFeature([], tf.string),
    "label":    tf.io.FixedLenFeature([], tf.string),
    "height":   tf.io.FixedLenFeature([], tf.int64),
    "width":    tf.io.FixedLenFeature([], tf.int64),
    "channels": tf.io.FixedLenFeature([], tf.int64),
}

IMG_SIZE = 96
BATCH    = 32
AUTOTUNE = tf.data.AUTOTUNE

def safe_parse(raw_bytes):
    """
    Returns (img [96,96,3] float32, label scalar float32).
    Returns sentinel (zeros, -1) for any corrupt record so we can filter them.
    """
    try:
        example = tf.train.Example()
        example.ParseFromString(raw_bytes.numpy())
        feats = example.features.feature

        h = int(feats["height"].int64_list.value[0])
        w = int(feats["width"].int64_list.value[0])
        c = int(feats["channels"].int64_list.value[0])

        img_bytes  = feats["image"].bytes_list.value[0]
        mask_bytes = feats["label"].bytes_list.value[0]

        # Validate byte counts before reshape
        expected_img  = h * w * c * 2   # float16 = 2 bytes
        expected_mask = h * w           # uint8   = 1 byte
        if len(img_bytes) != expected_img or len(mask_bytes) != expected_mask:
            return (
                np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.float32),
                np.array(-1.0, dtype=np.float32)   # sentinel
            )

        img  = np.frombuffer(img_bytes,  dtype=np.float16).reshape(h, w, c).astype(np.float32)
        mask = np.frombuffer(mask_bytes, dtype=np.uint8 ).reshape(h, w)  .astype(np.float32)

        # Normalise
        img_max = img.max()
        if img_max > 0:
            img = img / img_max
        img = np.clip(img, 0.0, 1.0)

        # Resize both to IMG_SIZE using PIL (no TF graph issues)
        from PIL import Image as PILImage
        img_pil  = np.stack([
            np.array(PILImage.fromarray(img[:,:,ch]).resize(
                (IMG_SIZE, IMG_SIZE), PILImage.Resampling.BILINEAR))
            for ch in range(c)
        ], axis=-1)
        mask_pil = np.array(
            PILImage.fromarray(mask).resize(
                (IMG_SIZE, IMG_SIZE), PILImage.Resampling.NEAREST))

        img_pil  = np.clip(img_pil, 0.0, 1.0).astype(np.float32)
        label    = np.float32(mask_pil.mean() > 0.2)

        return img_pil, label

    except Exception:
        return (
            np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.float32),
            np.array(-1.0, dtype=np.float32)   # sentinel
        )


def parse_tfrecord(raw_bytes):
    img, label = tf.py_function(
        func=safe_parse,
        inp=[raw_bytes],
        Tout=[tf.float32, tf.float32]
    )
    img.set_shape([IMG_SIZE, IMG_SIZE, 3])
    label.set_shape([])
    return img, label


def augment(img, label):
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_flip_up_down(img)
    img = tf.image.random_brightness(img, 0.15)
    img = tf.image.random_contrast(img, 0.8, 1.2)
    img = tf.clip_by_value(img, 0.0, 1.0)
    return img, label


def make_dataset(directory, augment_data=False, shuffle=False):
    files = (
        glob.glob(os.path.join(directory, "Cloudy",    "*.tfrecord")) +
        glob.glob(os.path.join(directory, "NonCloudy", "*.tfrecord"))
    )
    assert files, f"No TFRecords found under {directory}"
    print(f"  Loaded {len(files)} files from {os.path.basename(directory)}/")

    ds = tf.data.TFRecordDataset(files, num_parallel_reads=AUTOTUNE)
    ds = ds.map(parse_tfrecord, num_parallel_calls=AUTOTUNE)

    # Drop corrupt records (label == -1)
    ds = ds.filter(lambda img, label: label >= 0)

    if augment_data:
        ds = ds.map(augment, num_parallel_calls=AUTOTUNE)
    if shuffle:
        ds = ds.shuffle(buffer_size=2000, reshuffle_each_iteration=True)
    ds = ds.batch(BATCH).prefetch(AUTOTUNE)
    return ds


train_ds = make_dataset(TRAIN_DIR, augment_data=True,  shuffle=True)
val_ds   = make_dataset(VAL_DIR,   augment_data=False, shuffle=False)
test_ds  = make_dataset(TEST_DIR,  augment_data=False, shuffle=False)

# Sanity check
for imgs, labels in train_ds.take(1):
    print("Batch shape  :", imgs.shape)        # expect (32, 96, 96, 3)
    print("Pixel range  :", imgs.numpy().min().round(3), "-", imgs.numpy().max().round(3))
    print("Cloudy ratio :", labels.numpy().mean().round(3))

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 4 — Build model                                    ║
# ╚══════════════════════════════════════════════════════════╝
def build_model(input_shape=(IMG_SIZE, IMG_SIZE, 3), freeze_base=True):
    base = tf.keras.applications.MobileNetV2(
        input_shape=input_shape,
        include_top=False,
        weights="imagenet"
    )
    base.trainable = not freeze_base

    inputs = tf.keras.Input(shape=input_shape)
    # Images are already [0,1] from safe_parse — scale to [0,255] for
    # MobileNetV2's preprocess_input which maps to [-1,1] internally
    x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs * 255.0)
    x = base(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inputs, outputs)
    return model, base

model, base_model = build_model(freeze_base=True)
model.summary()

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 5 — Phase 1: Train head only (with label smoothing)║
# ╚══════════════════════════════════════════════════════════╝
# Label smoothing=0.1 means instead of training toward hard
# 0 and 1 targets, we train toward 0.1 and 0.9 — this
# directly prevents the model outputting 0.9999/0.0001

loss_fn = tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1)

model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-3),
    loss=loss_fn,
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

cb_ckpt = callbacks.ModelCheckpoint(
    CKPT_PATH, monitor="val_accuracy",
    save_best_only=True,
    save_weights_only=True,
    verbose=1
)
cb_early = callbacks.EarlyStopping(
    monitor="val_accuracy", patience=5,
    restore_best_weights=True, verbose=1
)
cb_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5,
    patience=3, min_lr=1e-6, verbose=1
)

print("=== Phase 1: head-only training ===")
history_1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10,
    callbacks=[cb_ckpt, cb_early, cb_lr]
)

# ── Check if phase 1 already achieved perfect val accuracy ──
best_val_acc_phase1 = max(history_1.history["val_accuracy"])
print(f"\nBest val accuracy after phase 1 : {best_val_acc_phase1:.4f}")
if best_val_acc_phase1 >= 0.995:
    print("► Phase 1 already saturated — check if phase 2 is needed")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 6c — Corrected temperature scaling                 ║
# ║  Run this AFTER retraining with label_smoothing=0.1      ║
# ╚══════════════════════════════════════════════════════════╝

# First check if probabilities are spread enough for scaling to work
prob_std = np.std(keras_pred_prob)
prob_min = keras_pred_prob.min()
prob_max = keras_pred_prob.max()

print(f"Probability spread check:")
print(f"  min={prob_min:.4f}  max={prob_max:.4f}  std={prob_std:.4f}")

if prob_std < 0.05:
    print("  ✗ Probabilities too collapsed — temperature scaling won't work.")
    print("  ► Retrain with label_smoothing=0.1 first, then re-run this cell.")
    CALIBRATION_T = 1.0   # neutral — no scaling
else:
    print("  ✓ Sufficient spread — running temperature search\n")

    # Search T in range appropriate for overconfident models
    temperatures = np.arange(0.1, 10.0, 0.05)
    nlls = []

    for T in temperatures:
        logits       = np.log(keras_pred_prob / (1 - keras_pred_prob + 1e-7) + 1e-7)
        scaled_probs = tf.sigmoid(logits / T).numpy()
        scaled_probs = np.clip(scaled_probs, 1e-7, 1 - 1e-7)
        nll = -np.mean(
            keras_true * np.log(scaled_probs) +
            (1 - keras_true) * np.log(1 - scaled_probs)
        )
        nlls.append(nll)

    best_T   = temperatures[np.argmin(nlls)]
    best_nll = min(nlls)

    print(f"  Best T   = {best_T:.2f}")
    print(f"  Best NLL = {best_nll:.6f}")

    if best_T < 1.0:
        print("  ⚠ T < 1 still — model outputs still collapsed.")
        print("    Increase label_smoothing to 0.15 and retrain.")
        CALIBRATION_T = 1.0
    elif best_T > 1.0:
        print(f"  ✓ T > 1 confirms overconfidence — scaling by {best_T:.2f} will fix it.")
        CALIBRATION_T = best_T

    # Plot NLL curve so you can see the minimum clearly
    plt.figure(figsize=(8, 4))
    plt.plot(temperatures, nlls, color="#185FA5", lw=2)
    plt.axvline(best_T, color="#D85A30", linestyle="--",
                label=f"Best T = {best_T:.2f}")
    plt.axvline(1.0, color="#888", linestyle=":",
                label="T=1 (no scaling)")
    plt.xlabel("Temperature T")
    plt.ylabel("Negative log likelihood")
    plt.title("Temperature search — lower NLL = better calibration")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("/content/temperature_search.png", dpi=150)
    plt.show()

    print(f"\n► CALIBRATION_T = {CALIBRATION_T:.2f}")
    print(f"  Apply in TFLite deployment:")
    print(f"    logit      = log(raw_prob / (1 - raw_prob))")
    print(f"    calibrated = 1 / (1 + exp(-logit / {CALIBRATION_T:.2f}))")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 6c — Corrected temperature scaling                 ║
# ║  Run this AFTER retraining with label_smoothing=0.1      ║
# ╚══════════════════════════════════════════════════════════╝

# First check if probabilities are spread enough for scaling to work
prob_std = np.std(keras_pred_prob)
prob_min = keras_pred_prob.min()
prob_max = keras_pred_prob.max()

print(f"Probability spread check:")
print(f"  min={prob_min:.4f}  max={prob_max:.4f}  std={prob_std:.4f}")

if prob_std < 0.05:
    print("  ✗ Probabilities too collapsed — temperature scaling won't work.")
    print("  ► Retrain with label_smoothing=0.1 first, then re-run this cell.")
    CALIBRATION_T = 1.0   # neutral — no scaling
else:
    print("  ✓ Sufficient spread — running temperature search\n")

    # Search T in range appropriate for overconfident models
    temperatures = np.arange(0.1, 10.0, 0.05)
    nlls = []

    for T in temperatures:
        logits       = np.log(keras_pred_prob / (1 - keras_pred_prob + 1e-7) + 1e-7)
        scaled_probs = tf.sigmoid(logits / T).numpy()
        scaled_probs = np.clip(scaled_probs, 1e-7, 1 - 1e-7)
        nll = -np.mean(
            keras_true * np.log(scaled_probs) +
            (1 - keras_true) * np.log(1 - scaled_probs)
        )
        nlls.append(nll)

    best_T   = temperatures[np.argmin(nlls)]
    best_nll = min(nlls)

    print(f"  Best T   = {best_T:.2f}")
    print(f"  Best NLL = {best_nll:.6f}")

    if best_T < 1.0:
        print("  ⚠ T < 1 still — model outputs still collapsed.")
        print("    Increase label_smoothing to 0.15 and retrain.")
        CALIBRATION_T = 1.0
    elif best_T > 1.0:
        print(f"  ✓ T > 1 confirms overconfidence — scaling by {best_T:.2f} will fix it.")
        CALIBRATION_T = best_T

    # Plot NLL curve so you can see the minimum clearly
    plt.figure(figsize=(8, 4))
    plt.plot(temperatures, nlls, color="#185FA5", lw=2)
    plt.axvline(best_T, color="#D85A30", linestyle="--",
                label=f"Best T = {best_T:.2f}")
    plt.axvline(1.0, color="#888", linestyle=":",
                label="T=1 (no scaling)")
    plt.xlabel("Temperature T")
    plt.ylabel("Negative log likelihood")
    plt.title("Temperature search — lower NLL = better calibration")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("/content/temperature_search.png", dpi=150)
    plt.show()

    print(f"\n► CALIBRATION_T = {CALIBRATION_T:.2f}")
    print(f"  Apply in TFLite deployment:")
    print(f"    logit      = log(raw_prob / (1 - raw_prob))")
    print(f"    calibrated = 1 / (1 + exp(-logit / {CALIBRATION_T:.2f}))")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 6 — Phase 2: Fine-tune top 30 layers               ║
# ╚══════════════════════════════════════════════════════════╝
base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

print(f"Trainable layers : {sum(1 for l in model.layers if l.trainable)}")
print(f"Frozen layers    : {sum(1 for l in model.layers if not l.trainable)}")

# Correctly calculate total_steps based on known dataset size
# Number of training samples is 1460 (from Cell 3 output)
total_train_samples = 1460 # Manually obtained from previous cell output for make_dataset(TRAIN_DIR)
total_steps = math.ceil(total_train_samples / BATCH) * 15
lr_schedule = optimizers.schedules.CosineDecay(
    initial_learning_rate=1e-5,
    decay_steps=total_steps,
    alpha=1e-7
)

model.compile(
    optimizer=optimizers.Adam(learning_rate=lr_schedule),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

cb_ckpt2 = callbacks.ModelCheckpoint(
    CKPT_PATH,
    monitor="val_accuracy",
    save_best_only=True,
    save_weights_only=True,
    verbose=1
)
cb_early2 = callbacks.EarlyStopping(
    monitor="val_accuracy", patience=5,
    restore_best_weights=True, verbose=1
)

print("=== Phase 2: fine-tuning top 30 layers ===")
history_2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=[cb_ckpt2, cb_early2]
)

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 6 — Phase 2: Conservative fine-tune               ║
# ╚══════════════════════════════════════════════════════════╝

# ── Gate: only run phase 2 if phase 1 didn't already max out─
PHASE1_THRESHOLD = 0.995

if best_val_acc_phase1 >= PHASE1_THRESHOLD:
    print(f"Phase 1 val accuracy = {best_val_acc_phase1:.4f} — "
          f"already at ceiling. Skipping phase 2.")
    print("Loading phase 1 best weights as final model.")
    history_2 = history_1   # reuse for plotting
else:
    print("Phase 1 did not saturate — proceeding with phase 2.")

    # Unfreeze only last 10 layers instead of 30
    # This is much more conservative — avoids the spike you saw
    base_model.trainable = True
    for layer in base_model.layers[:-10]:
        layer.trainable = False

    trainable   = sum(1 for l in model.layers if l.trainable)
    frozen      = sum(1 for l in model.layers if not l.trainable)
    print(f"Trainable layers : {trainable}")
    print(f"Frozen layers    : {frozen}")

    # Warmup + cosine decay
    # Warmup for first 3 epochs prevents the spike seen previously
    PHASE2_EPOCHS  = 15
    WARMUP_EPOCHS  = 3
    steps_per_epoch = len(train_ds)
    total_steps    = steps_per_epoch * PHASE2_EPOCHS
    warmup_steps   = steps_per_epoch * WARMUP_EPOCHS

    # Linear warmup from 1e-7 to 1e-5 then cosine decay to 1e-7
    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=1e-6,   # was 1e-5 — 10x lower
        decay_steps=total_steps - warmup_steps,
        alpha=1e-7,
        warmup_target=1e-5,
        warmup_steps=warmup_steps
    )

    model.compile(
        optimizer=optimizers.Adam(learning_rate=lr_schedule),
        loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
        metrics=[
            "accuracy",
            tf.keras.metrics.AUC(name="auc"),
            tf.keras.metrics.Precision(name="precision"),
            tf.keras.metrics.Recall(name="recall")
        ]
    )

    cb_ckpt2 = callbacks.ModelCheckpoint(
        CKPT_PATH, monitor="val_accuracy",
        save_best_only=True,
        save_weights_only=True,
        verbose=1
    )
    cb_early2 = callbacks.EarlyStopping(
        monitor="val_accuracy", patience=5,
        restore_best_weights=True, verbose=1
    )

    print("=== Phase 2: conservative fine-tuning (top 10 layers) ===")
    history_2 = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=PHASE2_EPOCHS,
        callbacks=[cb_ckpt2, cb_early2]
    )

    best_val_acc_phase2 = max(history_2.history["val_accuracy"])
    print(f"\nBest val accuracy phase 1 : {best_val_acc_phase1:.4f}")
    print(f"Best val accuracy phase 2 : {best_val_acc_phase2:.4f}")
    if best_val_acc_phase2 <= best_val_acc_phase1:
        print("► Phase 2 gave no improvement — phase 1 weights are used (best checkpoint)")
    else:
        print(f"► Phase 2 improved by {(best_val_acc_phase2-best_val_acc_phase1)*100:.2f}%")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 6b — Cross-validation + robustness check           ║
# ╚══════════════════════════════════════════════════════════╝
from sklearn.model_selection import StratifiedKFold
import gc

# ── Part A: 5-fold cross validation on train+val ─────────────
print("=" * 55)
print("  PART A: 5-FOLD CROSS VALIDATION")
print("=" * 55)
print("This checks if the model's performance is stable")
print("across different random splits of your data.\n")

# Collect all train+val data into numpy arrays
print("Loading train+val into memory for CV...")
all_imgs, all_labels = [], []
for imgs, labels in train_ds:
    all_imgs.append(imgs.numpy())
    all_labels.append(labels.numpy())
for imgs, labels in val_ds:
    all_imgs.append(imgs.numpy())
    all_labels.append(labels.numpy())

all_imgs   = np.concatenate(all_imgs,   axis=0)   # (N, 96, 96, 3)
all_labels = np.concatenate(all_labels, axis=0)   # (N,)

print(f"Total samples for CV : {len(all_imgs)}")
print(f"Cloudy    : {int(all_labels.sum())}  ({all_labels.mean()*100:.1f}%)")
print(f"NonCloudy : {int((1-all_labels).sum())}  ({(1-all_labels.mean())*100:.1f}%)\n")

skf        = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_accs  = []
fold_f1s   = []

for fold, (train_idx, val_idx) in enumerate(skf.split(all_imgs, all_labels)):
    print(f"  Fold {fold+1}/5 ", end="", flush=True)

    # Build a fresh model for each fold
    fold_model, _ = build_model(freeze_base=True)
    fold_model.compile(
        optimizer=optimizers.Adam(learning_rate=1e-3),
        loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
        metrics=["accuracy"]
    )

    X_tr, X_val = all_imgs[train_idx],   all_imgs[val_idx]
    y_tr, y_val = all_labels[train_idx], all_labels[val_idx]

    # Create tf.data datasets for this fold
    fold_train_ds = (tf.data.Dataset.from_tensor_slices((X_tr, y_tr))
                     .shuffle(1000).batch(BATCH).prefetch(AUTOTUNE))
    fold_val_ds   = (tf.data.Dataset.from_tensor_slices((X_val, y_val))
                     .batch(BATCH).prefetch(AUTOTUNE))

    fold_model.fit(
        fold_train_ds,
        validation_data=fold_val_ds,
        epochs=10,
        verbose=0,
        callbacks=[callbacks.EarlyStopping(
            monitor="val_accuracy", patience=3,
            restore_best_weights=True)]
    )

    # Evaluate
    preds     = fold_model.predict(fold_val_ds, verbose=0).flatten()
    pred_bin  = (preds > 0.5).astype(int)
    acc       = (pred_bin == y_val).mean()
    f1        = f1_score(y_val, pred_bin, average="weighted")
    fold_accs.append(acc)
    fold_f1s.append(f1)
    print(f"acc={acc:.4f}  F1={f1:.4f}")

    # Free memory
    del fold_model, fold_train_ds, fold_val_ds
    gc.collect()
    tf.keras.backend.clear_session()

print(f"\n  CV Accuracy : {np.mean(fold_accs):.4f} ± {np.std(fold_accs):.4f}")
print(f"  CV F1 score : {np.mean(fold_f1s):.4f} ± {np.std(fold_f1s):.4f}")

if np.std(fold_accs) < 0.02:
    print("  ✓ Low variance — model is stable across splits")
elif np.std(fold_accs) < 0.05:
    print("  ⚠ Moderate variance — collect more data if possible")
else:
    print("  ✗ High variance — model is unstable, dataset too small")

# ── Part B: Augmentation stress test ─────────────────────────
print("\n" + "=" * 55)
print("  PART B: AUGMENTATION STRESS TEST")
print("=" * 55)
print("Tests robustness by applying heavy augmentation to test set")
print("A robust model should degrade < 5% under stress.\n")

# Rebuild best model for this test
stress_model, _ = build_model(freeze_base=False)
stress_model.load_weights(CKPT_PATH)

def heavy_augment_batch(imgs):
    """Apply aggressive augmentation to a batch"""
    imgs = tf.image.random_flip_left_right(imgs)
    imgs = tf.image.random_flip_up_down(imgs)
    imgs = tf.image.random_brightness(imgs, 0.3)     # stronger than training
    imgs = tf.image.random_contrast(imgs, 0.6, 1.4)  # stronger than training
    imgs = tf.image.random_saturation(imgs, 0.7, 1.3)
    imgs = tf.clip_by_value(imgs, 0.0, 1.0)
    return imgs

stress_true, stress_pred = [], []
for imgs, labels in test_ds:
    imgs_aug = heavy_augment_batch(imgs)
    preds    = stress_model.predict(imgs_aug, verbose=0).flatten()
    stress_pred.extend((preds > 0.5).astype(int).tolist())
    stress_true.extend(labels.numpy().astype(int).tolist())

stress_acc = (np.array(stress_pred) == np.array(stress_true)).mean()
drop       = (keras_acc - stress_acc) * 100

print(f"  Normal test accuracy       : {keras_acc:.4f}")
print(f"  Stress augmented accuracy  : {stress_acc:.4f}")
print(f"  Accuracy drop under stress : {drop:.2f}%")

if drop < 2.0:
    print("  ✓ Model is robust to image perturbations")
elif drop < 5.0:
    print("  ⚠ Mild sensitivity — add stronger augmentation in training")
else:
    print("  ✗ High sensitivity — model relies on exact image statistics")

# ── Part C: Temperature scaling for calibration ──────────────
print("\n" + "=" * 55)
print("  PART C: TEMPERATURE SCALING (fix overconfidence)")
print("=" * 55)
print("Finds optimal T so that predicted probabilities are")
print("better calibrated (0.8 prediction = 80% actual accuracy)\n")

temperatures = np.arange(0.5, 8.0, 0.1)
best_nll, best_T = float("inf"), 1.0

for T in temperatures:
    logits       = np.log(keras_pred_prob / (1 - keras_pred_prob + 1e-7) + 1e-7)
    scaled_probs = 1 / (1 + np.exp(-logits / T))
    nll          = -np.mean(
        keras_true * np.log(scaled_probs + 1e-7) +
        (1 - keras_true) * np.log(1 - scaled_probs + 1e-7)
    )
    if nll < best_nll:
        best_nll, best_T = nll, T

# Apply best temperature
logits_scaled  = np.log(keras_pred_prob / (1 - keras_pred_prob + 1e-7) + 1e-7)
calibrated_prob = 1 / (1 + np.exp(-logits_scaled / best_T))

print(f"  Best temperature T = {best_T:.1f}")
print(f"  (T > 1 means model was overconfident, T=1 means well calibrated)")

# Plot before/after calibration
from sklearn.calibration import calibration_curve
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, probs, title in [
    (axes[0], keras_pred_prob, "Before calibration (raw)"),
    (axes[1], calibrated_prob, f"After calibration (T={best_T:.1f})")
]:
    prob_true, prob_pred = calibration_curve(keras_true, probs, n_bins=10)
    ax.plot(prob_pred, prob_true, "s-", color="#185FA5", label="Model")
    ax.plot([0,1],[0,1], "k--", lw=1, label="Perfect")
    ax.fill_between(prob_pred, prob_true, prob_pred,
                    alpha=0.15, color="#D85A30", label="Gap")
    ax.set_xlabel("Mean predicted probability")
    ax.set_ylabel("Fraction of positives")
    ax.set_title(title)
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Also plot confidence distribution
    cloudy_p    = probs[keras_true == 1]
    noncloudy_p = probs[keras_true == 0]

plt.tight_layout()
plt.savefig("/content/calibration_before_after.png", dpi=150)
plt.show()

# Save the temperature value for use in deployment
CALIBRATION_T = best_T
print(f"\n  ► In your TFLite deployment, apply this after inference:")
print(f"    raw_prob    = model_output")
print(f"    logit       = log(raw_prob / (1 - raw_prob))")
print(f"    calibrated  = 1 / (1 + exp(-logit / {best_T:.1f}))")
print(f"    prediction  = 1 if calibrated > 0.5 else 0")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 7 — Plot training curves                           ║
# ╚══════════════════════════════════════════════════════════╝
def plot_history(h1, h2):
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))
    metrics = ["accuracy", "loss"]
    colors  = {"train": "#185FA5", "val": "#D85A30"}

    for ax, metric in zip(axes, metrics):
        v1     = h1.history.get(metric, [])
        v1_val = h1.history.get(f"val_{metric}", [])
        v2     = h2.history.get(metric, [])
        v2_val = h2.history.get(f"val_{metric}", [])

        combined     = v1 + v2
        combined_val = v1_val + v2_val
        split        = len(v1)
        xs           = list(range(1, len(combined) + 1))

        ax.plot(xs, combined,     color=colors["train"], label="train")
        ax.plot(xs, combined_val, color=colors["val"],   label="val", linestyle="--")
        ax.axvline(split, color="#888", linestyle=":", linewidth=1, label="unfreeze")
        ax.set_title(metric.capitalize())
        ax.set_xlabel("Epoch")
        ax.legend()
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("/content/training_curves.png", dpi=150)
    plt.show()

plot_history(history_1, history_2)

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 8 — Evaluate best checkpoint on test set           ║
# ╚══════════════════════════════════════════════════════════╝

# Rebuild the exact same architecture from Cell 4
best_model, _ = build_model(freeze_base=False)

# Load only the weights — avoids TrueDivide deserialization entirely
best_model.load_weights(CKPT_PATH)

best_model.compile(
    optimizer=optimizers.Adam(),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

y_true, y_pred_prob = [], []
for imgs, labels in test_ds:
    preds = best_model.predict(imgs, verbose=0).flatten()
    y_pred_prob.extend(preds.tolist())
    y_true.extend(labels.numpy().tolist())

y_true      = np.array(y_true)
y_pred_prob = np.array(y_pred_prob)
y_pred      = (y_pred_prob > 0.5).astype(int)

print("\n===== Test Set Evaluation =====")
print(classification_report(y_true, y_pred, target_names=["NonCloudy", "Cloudy"]))

cm   = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["NonCloudy", "Cloudy"])
disp.plot(cmap="Blues")
plt.title("Confusion matrix — test set")
plt.savefig("/content/confusion_matrix.png", dpi=150)
plt.show()

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 9 — Post-training full-integer quantization        ║
# ╚══════════════════════════════════════════════════════════╝
rep_samples = []
for imgs, _ in val_ds.unbatch().take(100):
    rep_samples.append(imgs.numpy())

rep_array = np.array(rep_samples, dtype=np.float32)   # (100, 96, 96, 3)

def representative_dataset():
    for sample in rep_array:
        yield [sample[np.newaxis, ...]]                # (1, 96, 96, 3)

# Use concrete function instead of from_keras_model to avoid TrueDivide issue
@tf.function(input_signature=[tf.TensorSpec(shape=[1, IMG_SIZE, IMG_SIZE, 3], dtype=tf.float32)])
def serving_fn(x):
    return best_model(x, training=False)

converter = tf.lite.TFLiteConverter.from_concrete_functions(
    [serving_fn.get_concrete_function()]
)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type  = tf.float32
converter.inference_output_type = tf.float32

tflite_model = converter.convert()

with open(TFLITE_OUT, "wb") as f:
    f.write(tflite_model)

size_kb = os.path.getsize(TFLITE_OUT) / 1024
print(f"\nTFLite model saved → {TFLITE_OUT}")
print(f"File size : {size_kb:.1f} KB  ({size_kb/1024:.2f} MB)")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 10 — Test MobileNetV2 + TFLite on test set         ║
# ╚══════════════════════════════════════════════════════════╝

# ── Part A: MobileNetV2 model on test set ────────────────────
print("=" * 50)
print("  MobileNetV2 — Test Set Evaluation")
print("=" * 50)

keras_true, keras_pred_prob = [], []
for imgs, labels in test_ds:
    preds = best_model.predict(imgs, verbose=0).flatten()
    keras_pred_prob.extend(preds.tolist())
    keras_true.extend(labels.numpy().tolist())

keras_true      = np.array(keras_true)
keras_pred_prob = np.array(keras_pred_prob)
keras_pred      = (keras_pred_prob > 0.5).astype(int)

print(classification_report(keras_true, keras_pred, target_names=["NonCloudy", "Cloudy"]))

cm_keras = confusion_matrix(keras_true, keras_pred)
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
ConfusionMatrixDisplay(cm_keras, display_labels=["NonCloudy", "Cloudy"]).plot(
    ax=axes[0], cmap="Blues", colorbar=False
)
axes[0].set_title("MobileNetV2 — test set")

# ── Part B: MobileNetV2 TFLite on test set ───────────────────
print("=" * 50)
print("  MobileNetV2 TFLite (int8) — Test Set Evaluation")
print("=" * 50)

interpreter = tf.lite.Interpreter(model_path=TFLITE_OUT)
interpreter.allocate_tensors()

input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"Input  shape/dtype : {input_details[0]['shape']}  {input_details[0]['dtype']}")
print(f"Output shape/dtype : {output_details[0]['shape']}  {output_details[0]['dtype']}")

tfl_true, tfl_pred_prob = [], []
for imgs, labels in test_ds:
    for i in range(imgs.shape[0]):
        inp = imgs[i:i+1].numpy().astype(np.float32)
        interpreter.set_tensor(input_details[0]['index'], inp)
        interpreter.invoke()
        out = interpreter.get_tensor(output_details[0]['index'])[0][0]
        tfl_pred_prob.append(float(out))
        tfl_true.append(int(labels[i].numpy()))

tfl_true      = np.array(tfl_true)
tfl_pred_prob = np.array(tfl_pred_prob)
tfl_pred      = (tfl_pred_prob > 0.5).astype(int)

print(classification_report(tfl_true, tfl_pred, target_names=["NonCloudy", "Cloudy"]))

cm_tfl = confusion_matrix(tfl_true, tfl_pred)
ConfusionMatrixDisplay(cm_tfl, display_labels=["NonCloudy", "Cloudy"]).plot(
    ax=axes[1], cmap="Greens", colorbar=False
)
axes[1].set_title("MobileNetV2 TFLite (int8) — test set")

plt.tight_layout()
plt.savefig("/content/confusion_matrices.png", dpi=150)
plt.show()

# ── Part C: Side-by-side comparison ──────────────────────────
print("=" * 50)
print("  MobileNetV2 vs MobileNetV2 TFLite (int8)")
print("=" * 50)

keras_acc = (keras_pred == keras_true).mean()
tfl_acc   = (tfl_pred   == tfl_true).mean()
drop      = (keras_acc  - tfl_acc) * 100

print(f"  MobileNetV2        accuracy : {keras_acc:.4f}  ({keras_acc*100:.2f}%)")
print(f"  MobileNetV2 TFLite accuracy : {tfl_acc:.4f}  ({tfl_acc*100:.2f}%)")
print(f"  Accuracy drop (quantization): {drop:.2f}%  ({'OK' if drop < 1.0 else 'REVIEW — drop > 1%'})")

from sklearn.metrics import f1_score
keras_f1 = f1_score(keras_true, keras_pred, average="weighted")
tfl_f1   = f1_score(tfl_true,   tfl_pred,   average="weighted")
print(f"  MobileNetV2        F1 (weighted) : {keras_f1:.4f}")
print(f"  MobileNetV2 TFLite F1 (weighted) : {tfl_f1:.4f}")

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 11 — Visualise sample predictions                  ║
# ╚══════════════════════════════════════════════════════════╝
fig, axes = plt.subplots(2, 8, figsize=(20, 6))
labels_str   = ["NonCloudy", "Cloudy"]
class_colors = {"correct": "#1D9E75", "wrong": "#D85A30"}

sample_imgs, sample_labels = next(iter(test_ds.unbatch().batch(16)))
sample_imgs   = sample_imgs.numpy()
sample_labels = sample_labels.numpy().astype(int)

for idx, ax in enumerate(axes.flat):
    if idx >= len(sample_imgs):
        ax.axis("off")
        continue

    inp = sample_imgs[idx:idx+1].astype(np.float32)   # already [0,1]
    interpreter.set_tensor(input_details[0]['index'], inp)
    interpreter.invoke()
    prob = interpreter.get_tensor(output_details[0]['index'])[0][0]
    pred = int(prob > 0.5)

    ax.imshow(sample_imgs[idx])                        # [0,1] displays correctly
    ax.axis("off")

    color  = class_colors["correct"] if pred == sample_labels[idx] else class_colors["wrong"]
    status = "✓" if pred == sample_labels[idx] else "✗"
    ax.set_title(f"{status} {labels_str[pred]}\n{prob:.2f}", fontsize=8, color=color)

plt.suptitle("TFLite predictions — green=correct, red=wrong", y=1.01)
plt.tight_layout()
plt.savefig("/content/sample_predictions.png", dpi=150)
plt.show()

from google.colab import files

# TFLITE_OUT is defined in Cell 2 as '/content/drive/MyDrive/cloud_classifier.tflite'
# However, it was saved to the current Colab environment in Cell 9.
# To download the file that was just created, we need to ensure it's accessible.
# If it was saved directly to Drive, it would already be there.
# Assuming TFLITE_OUT also points to the locally saved file in this context for download.

# If TFLITE_OUT is directly accessible in the Colab file system
files.download(TFLITE_OUT)

# ╔══════════════════════════════════════════════════════════╗
# ║  CELL 12 — Overfitting & imbalance diagnostics           ║
# ╚══════════════════════════════════════════════════════════╝
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import (
    classification_report, confusion_matrix,
    ConfusionMatrixDisplay, roc_curve, auc,
    precision_recall_curve, average_precision_score
)
from sklearn.calibration import calibration_curve

# ── 1. Dataset class distribution ────────────────────────────
print("=" * 55)
print("  1. CLASS DISTRIBUTION ACROSS SPLITS")
print("=" * 55)

for name, ds in [("train", train_ds), ("val", val_ds), ("test", test_ds)]:
    all_labels = np.concatenate([labels.numpy() for _, labels in ds])
    n_total   = len(all_labels)
    n_cloudy  = int(all_labels.sum())
    n_clear   = n_total - n_cloudy
    ratio     = n_cloudy / n_total
    print(f"  {name:6s} → total={n_total:4d}  "
          f"Cloudy={n_cloudy:4d} ({ratio*100:.1f}%)  "
          f"NonCloudy={n_clear:4d} ({(1-ratio)*100:.1f}%)")

# ── 2. Train vs Val accuracy gap (overfitting signal) ────────
print("\n" + "=" * 55)
print("  2. TRAIN vs VAL ACCURACY GAP")
print("=" * 55)

final_train_acc = history_2.history["accuracy"][-1]
final_val_acc   = history_2.history["val_accuracy"][-1]
best_val_acc    = max(history_2.history["val_accuracy"])
gap             = final_train_acc - final_val_acc

print(f"  Final train accuracy : {final_train_acc:.4f}")
print(f"  Final val   accuracy : {final_val_acc:.4f}")
print(f"  Best  val   accuracy : {best_val_acc:.4f}")
print(f"  Train-val gap        : {gap:.4f}", end="  ")
if gap < 0.05:
    print("✓ No significant overfitting")
elif gap < 0.10:
    print("⚠ Mild overfitting — monitor closely")
else:
    print("✗ Overfitting detected — consider more dropout/augmentation")

# ── 3. Per-class metrics (catches imbalance masking) ─────────
print("\n" + "=" * 55)
print("  3. PER-CLASS METRICS ON TEST SET")
print("=" * 55)
print(classification_report(
    keras_true, keras_pred,
    target_names=["NonCloudy", "Cloudy"],
    digits=4
))
print("  ► If minority class F1 << majority class F1,")
print("    the model is biased toward the majority class.")

# ── 4. ROC curve + AUC ───────────────────────────────────────
fpr, tpr, roc_thresh = roc_curve(keras_true, keras_pred_prob)
roc_auc = auc(fpr, tpr)

# ── 5. Precision-Recall curve (best for imbalanced data) ─────
precision, recall, pr_thresh = precision_recall_curve(keras_true, keras_pred_prob)
avg_precision = average_precision_score(keras_true, keras_pred_prob)
# Baseline = fraction of positive class
baseline = keras_true.mean()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plot ROC
axes[0].plot(fpr, tpr, color="#185FA5", lw=2, label=f"AUC = {roc_auc:.4f}")
axes[0].plot([0,1],[0,1], "k--", lw=1, label="Random classifier")
axes[0].fill_between(fpr, tpr, alpha=0.08, color="#185FA5")
axes[0].set_xlabel("False Positive Rate")
axes[0].set_ylabel("True Positive Rate")
axes[0].set_title("ROC Curve")
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Plot PR curve
axes[1].plot(recall, precision, color="#1D9E75", lw=2, label=f"AP = {avg_precision:.4f}")
axes[1].axhline(baseline, color="#D85A30", lw=1, linestyle="--",
                label=f"Baseline (random) = {baseline:.2f}")
axes[1].set_xlabel("Recall")
axes[1].set_ylabel("Precision")
axes[1].set_title("Precision-Recall Curve")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# Plot confidence distribution per class
cloudy_probs    = keras_pred_prob[keras_true == 1]
noncloudy_probs = keras_pred_prob[keras_true == 0]
axes[2].hist(noncloudy_probs, bins=30, alpha=0.6, color="#185FA5",
             label="NonCloudy (true)", density=True)
axes[2].hist(cloudy_probs,    bins=30, alpha=0.6, color="#D85A30",
             label="Cloudy (true)",    density=True)
axes[2].axvline(0.5, color="black", lw=1.5, linestyle="--", label="threshold=0.5")
axes[2].set_xlabel("Predicted probability")
axes[2].set_ylabel("Density")
axes[2].set_title("Confidence distribution per class")
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("/content/diagnostics_roc_pr_conf.png", dpi=150)
plt.show()

# ── 6. Calibration curve (is the model overconfident?) ───────
print("=" * 55)
print("  4. CALIBRATION CHECK")
print("=" * 55)

prob_true, prob_pred = calibration_curve(keras_true, keras_pred_prob, n_bins=10)

fig, ax = plt.subplots()

